### PR TITLE
feat: added a custom user-agent to the API connection configuration

### PR DESCRIPTION
**Pull request by alexal**
Closes https://github.com/redhat-developer/app-services-cli/issues/994

### CODE REVIEW

**Comment by wtrocki** [comment]
@craicoverflow would you envision this configs being different in the future. There is a lot of repetition for each SDK maybe config can be part of the common codebase?

**Review by wtrocki — APPROVED** [review]
Verified in CLI

**Comment by wtrocki** [comment]
This haven't been released yet. You can do PR in the CLI assuming that changes are there and we will provide release for it soon.

**Comment by craicoverflow** [comment]
> @craicoverflow would you envision this configs being different in the future. There is a lot of repetition for each SDK maybe config can be part of the common codebase?

When there was only a single module there was actually a single config in `internal`, where each SDK had its own type which was assigned to it like: `type Config = internal.APIConfig`. I had removed it to make the switch to multi-module easier but now that that is complete it can be brought back. This was not cause any breaking change if we follow the previous approach.

**Comment by wtrocki** [comment]
@craicoverflow actually I remember it. Since you have explained it let's keep it the way it was - it might be that SDK's will have different config at some point etc.

**Comment by craicoverflow** [comment]
https://github.com/redhat-developer/app-services-sdk-go/issues/261

Yeah, but the way it was done meant that we could easily diverge API configs in the future without causing a breaking change. So it is worth to have again.

**Pull request merged**
