### PR TITLE
chore: manual update for SDK's

### PR DESCRIPTION
**Pull request by wtrocki**
Based on the work with SRS team.

### CODE REVIEW

**Comment by wtrocki** [comment]
@craicoverflow can you help me how I can now generate SDK's - some instruction etc.

**Comment by craicoverflow** [comment]
Actually if you merge that it could be a way to validate if SDK will be generated on merge!

**Comment by wtrocki** [comment]
@craicoverflow feel free to do it. Btw. there might be breaking changes on this due to introduction of tag - Registry.

**Comment by wtrocki** [comment]
I think that having tags is actually going to be better ux. RegistryAPI works better than DefaultAPI in terms of UX

**Pull request merged**
