### PR TITLE
Accept header fix!

### PR DESCRIPTION
**Pull request by wtrocki**
This is tough example of codegeneration issues;

- I could not fix problem on the backend as from backend side things working fine
- I could not fix problem in generator (as generator doesn' support anything else than json and they force things intentionally)

This fix removes silly override that forces JSON accept header where others like zip file can exist

### CODE REVIEW

**Comment by wtrocki** [comment]
Question is how we handle this fix. We need to provide custom templates :/ in long run as it will be overridden later.

**Comment by craicoverflow** [comment]
> Question is how we handle this fix. We need to provide custom templates :/ in long run as it will be overridden later.

1. Propose the fix with a pull request to OpenAPI Generator. Clearly state the reason why this is a bug and how we should not be overriding headers like this.
2. Use template locally in the meantime and hope the PR gets accepted.

**Review by craicoverflow — APPROVED** [review]

**Comment by wtrocki** [comment]
Done fix but very low hopes on getting it merged: 

https://github.com/OpenAPITools/openapi-generator/pull/10337

Having issues with the templates (it is not possible to isolate templates to some small chunk of code so I need to push whole template which is going to case issues.

**Comment by wtrocki** [comment]
Instead of pushing tons of template files I settled with more smooth approach by removing 500 error code. API will still return errors normally and they will be parsed just fine but this time Accept header problem is mitigated.

**Pull request merged**
