### PR TITLE
Command line client for releng

### PR DESCRIPTION
**Pull request by wtrocki**
Simple clean solution that will be generic enough and can work with env vars and arguments. 
It gives us way to share code across repository and reuse some of the utils like fetching various elements from github etc.

### CODE REVIEW

**Comment by wtrocki** [comment]
I will get fetch and generate for this done.
@craicoverflow Let's chat about this next week.

**Comment by wtrocki** [comment]
I sleept thru this and I think we overengineered very simple problem. 

1. We need OpenAPI update (PR with OpenAPI file)
2. We need way to generate all API in repo.

First one can be github action (using code that is in this PR for simplicity)
Second one can be simple bash script (No need for configs or any other stuff).

**Comment by craicoverflow** [comment]
> No need for configs or any other stuff

What configs do you mean?

**Comment by wtrocki** [comment]
.config folder. I have applied this pattern to js-sdk
https://github.com/aerogear/aerogear-js-sdk

**Comment by craicoverflow** [comment]
> .config folder. I have applied this pattern to js-sdk
> [aerogear/aerogear-js-sdk](https://github.com/aerogear/aerogear-js-sdk)

Not familiar with that library, maybe a TL;DR? Is this something you think is not needed for the Go SDK also?

**Comment by wtrocki** [comment]
sdk-js repo. Sorry

**Comment by craicoverflow** [comment]
closing as stale.

**Pull request closed without merging**
